language: node_js
node_js:
  - "stable"
cache:
  directories:
  - /dev/node_modules
script:
  - cd dev
  - npm install
  - npm test
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: /dev/build
  on:
    branch: master